### Get Health
GET https://phare-share-dev.privatelink.eastus2.azmk8s.io/api/v1/health

### Get User by ID
GET https://jsonplaceholder.typicode.com/users/1

### Create User
POST https://jsonplaceholder.typicode.com/users
Content-Type: application/json

{
  "name": "Jane Doe",
  "username": "janedoe",
  "email": "jane@example.com"
}

### Update User
PUT https://jsonplaceholder.typicode.com/users/1
Content-Type: application/json

{
  "name": "Jane Doe Updated",
  "username": "janedoe",
  "email": "jane.updated@example.com"
}

### Delete User
DELETE https://jsonplaceholder.typicode.com/users/1
