use crate::tui::app_states::AppState;
use crate::tui::app_states::AppState::*;

pub fn next_app_state(app_state: &AppState) -> AppState {
	match app_state {
		Normal => DisplayingEnvEditor,
		DisplayingEnvEditor => EditingEnvVariable,
		EditingEnvVariable => DisplayingCookies,
		DisplayingCookies => EditingCookies,
		EditingCookies => DisplayingLogs,
		DisplayingLogs => ChoosingElementToCreate,
		ChoosingElementToCreate => CreatingNewCollection,
		CreatingNewCollection => CreatingNewRequest,
		CreatingNewRequest => DeletingCollection,
		DeletingCollection => DeletingRequest,
		DeletingRequest => RenamingCollection,
		RenamingCollection => RenamingRequest,
		RenamingRequest => CreatingNewFolder,
		CreatingNewFolder => DeletingFolder,
		DeletingFolder => RenamingFolder,
		RenamingFolder => SelectedRequest,
		SelectedRequest => EditingRequestUrl,
		EditingRequestUrl => EditingRequestParam,
		EditingRequestParam => EditingRequestAuthBasicUsername,
		EditingRequestAuthBasicUsername => EditingRequestAuthBasicPassword,
		EditingRequestAuthBasicPassword => EditingRequestAuthBearerToken,
		EditingRequestAuthBearerToken => EditingRequestAuthJwtSecret,
		EditingRequestAuthJwtSecret => EditingRequestAuthJwtPayload,
		EditingRequestAuthJwtPayload => EditingRequestAuthDigestUsername,
		EditingRequestAuthDigestUsername => EditingRequestAuthDigestPassword,
		EditingRequestAuthDigestPassword => EditingRequestAuthDigestDomains,
		EditingRequestAuthDigestDomains => EditingRequestAuthDigestRealm,
		EditingRequestAuthDigestRealm => EditingRequestAuthDigestNonce,
		EditingRequestAuthDigestNonce => EditingRequestAuthDigestOpaque,
		EditingRequestAuthDigestOpaque => EditingRequestHeader,
		EditingRequestHeader => EditingRequestBodyTable,
		EditingRequestBodyTable => EditingRequestBodyFile,
		EditingRequestBodyFile => EditingRequestBodyString,
		EditingRequestBodyString => EditingRequestMessage,
		EditingRequestMessage => EditingGraphqlQuery,
		EditingGraphqlQuery => EditingGraphqlVariables,
		EditingGraphqlVariables => EditingPreRequestScript,
		EditingPreRequestScript => EditingPostRequestScript,
		EditingPostRequestScript => EditingRequestSettings,
		EditingRequestSettings => ChoosingRequestExportFormat,
		ChoosingRequestExportFormat => DisplayingRequestExport,
		DisplayingRequestExport => SelectingResponseBody,
		SelectingResponseBody => ChoosingTheme,
		ChoosingTheme => Normal,
	}
}

pub fn previous_app_state(app_state: &AppState) -> AppState {
	match app_state {
		Normal => EditingRequestSettings,
		DisplayingEnvEditor => Normal,
		EditingEnvVariable => DisplayingEnvEditor,
		DisplayingCookies => EditingEnvVariable,
		EditingCookies => DisplayingCookies,
		DisplayingLogs => EditingCookies,
		ChoosingElementToCreate => DisplayingLogs,
		CreatingNewCollection => ChoosingElementToCreate,
		CreatingNewRequest => CreatingNewCollection,
		DeletingCollection => CreatingNewRequest,
		DeletingRequest => DeletingCollection,
		RenamingCollection => DeletingRequest,
		RenamingRequest => RenamingCollection,
		SelectedRequest => RenamingFolder,
		RenamingFolder => DeletingFolder,
		DeletingFolder => CreatingNewFolder,
		CreatingNewFolder => RenamingRequest,
		EditingRequestUrl => SelectedRequest,
		EditingRequestParam => EditingRequestUrl,
		EditingRequestAuthBasicUsername => EditingRequestParam,
		EditingRequestAuthBasicPassword => EditingRequestAuthBasicUsername,
		EditingRequestAuthBearerToken => EditingRequestAuthBasicPassword,
		EditingRequestAuthJwtSecret => EditingRequestAuthBearerToken,
		EditingRequestAuthJwtPayload => EditingRequestAuthJwtSecret,
		EditingRequestAuthDigestUsername => EditingRequestAuthJwtPayload,
		EditingRequestAuthDigestPassword => EditingRequestAuthDigestUsername,
		EditingRequestAuthDigestDomains => EditingRequestAuthDigestPassword,
		EditingRequestAuthDigestRealm => EditingRequestAuthDigestDomains,
		EditingRequestAuthDigestNonce => EditingRequestAuthDigestRealm,
		EditingRequestAuthDigestOpaque => EditingRequestAuthDigestNonce,
		EditingRequestHeader => EditingRequestAuthDigestOpaque,
		EditingRequestBodyTable => EditingRequestHeader,
		EditingRequestBodyFile => EditingRequestBodyTable,
		EditingRequestBodyString => EditingRequestBodyFile,
		EditingRequestMessage => EditingRequestBodyString,
		EditingGraphqlQuery => EditingRequestMessage,
		EditingGraphqlVariables => EditingGraphqlQuery,
		EditingPreRequestScript => EditingGraphqlVariables,
		EditingPostRequestScript => EditingPreRequestScript,
		EditingRequestSettings => EditingPostRequestScript,
		ChoosingRequestExportFormat => EditingRequestSettings,
		DisplayingRequestExport => ChoosingRequestExportFormat,
		SelectingResponseBody => DisplayingRequestExport,
		ChoosingTheme => SelectingResponseBody,
	}
}
