name: Feature Request
description: Suggest a new feature or enhancement.
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe what you'd like and why.

  - type: textarea
    id: problem
    attributes:
      label: Problem or Motivation
      description: What problem does this solve, or what workflow does it improve?
      placeholder: "I often need to ... but currently ..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How do you think this should work? Include UI sketches, CLI examples, or API ideas if you have them.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any other approaches you've thought about or workarounds you currently use.
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Anything else — screenshots, links to similar tools, related issues, etc.
    validations:
      required: false
