### List Users
GET https://jsonplaceholder.typicode.com/users

### Get User by ID
GET https://jsonplaceholder.typicode.com/users/1

### Create User
POST https://jsonplaceholder.typicode.com/users
Content-Type: application/json

{
  "name": "Jane Doe",
  "username": "janedoe",
  "email": "jane@example.com"
}

### Update User
PUT https://jsonplaceholder.typicode.com/users/1
Content-Type: application/json

{
  "name": "Jane Doe Updated",
  "username": "janedoe",
  "email": "jane.updated@example.com"
}

### Delete User
DELETE https://jsonplaceholder.typicode.com/users/1

### Echo WebSocket
WEBSOCKET wss://echo.websocket.org/

### List Countries (GraphQL)
GRAPHQL https://countries.trevorblades.com/graphql

{
  countries {
    code
    name
    capital
    emoji
    currency
  }
}

### Say Hello (gRPC)
GRPC http://localhost:50051
X-Proto-File: proto/helloworld.proto
X-Grpc-Service: helloworld.Greeter
X-Grpc-Method: SayHello
Content-Type: application/grpc+json

{
  "name": "World"
}
